services:
  scambet:
    image: ghcr.io/alexprsk/prd.scambet:latest
    ports:
      - "8000:8000"
    env_file:
      - prod.env

    depends_on:
      - mongodb
      - postgresql

  scambetfront:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongodb
      - postgresql
      - scambet
      
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=scambet
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  mongodb_data:
  postgres_data:



