name: Build Frontend and Push Docker Image

run-name: Build and Push from branch ${{ github.ref_name }} by @${{ github.actor }}



  

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        
      - name: build-npm-action
        run :  npm install && npm run build

      - name: Set repository path
        run: |
          # Use lowercase repository path
          REPO_PATH=ghcr.io/$(echo "${{github.repository}}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_PATH=${REPO_PATH}" >> $GITHUB_ENV
          
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
              echo "IMAGE_NAME=prd-scambetfront" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "refs/heads/staging" ]; then
              echo "IMAGE_NAME=stg-scambetfront" >> $GITHUB_ENV
          fi
          echo "FULL_IMAGE=${REPO_PATH}/${IMAGE_NAME}" >> $GITHUB_ENV
          fi
          echo "Using image: $GH_REPO"

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: 'Build and Push Image'
        run: |
          echo "Building and pushing ${FULL_IMAGE}:latest"
          docker build -t ${FULL_IMAGE}:latest .
          docker push ${FULL_IMAGE}:latest

      - name: Run Cleanup Script
        run:  echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV


      - name: Generate summary
        run: |
          echo "### 🚀 Docker Image Build and Push Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Image**: \`${FULL_IMAGE}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Latest Tag**: \`${FULL_IMAGE}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Version Tag**: \`${FULL_IMAGE}:${{ github.run_number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pull Commands:" >> $GITHUB_STEP_SUMMARY
          echo "```bash" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${FULL_IMAGE}:latest" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${FULL_IMAGE}:${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY