name: Build Frontend and Push Docker Image

run-name: Build and Push from branch ${{ github.ref_name }} by @${{ github.actor }}

  

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        
      - name: build-npm-action
        run :  npm install && npm run build

      
      - name: Set Github Registry Repo
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
              echo "GHCR_REPO=ghcr.io/${{github.repository}}/prd.scambetfront" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "refs/heads/staging" ]; then
              echo "GHCR_REPO=ghcr.io/${{github.repository}}/stg.scambetfront" >> $GITHUB_ENV
          fi

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}


      - name: 'Build Inventory Image'
        run: |
          docker build -t GHCR_REPO:latest .
          docker push GHCR_REPO:latest

      - name: Run Cleanup Script
        run:  echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV


      - name: Generate and display summary
        run: |
          echo "### 🚀 Docker Image Build and Push Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Image Name**: \`$DOCKER_REPO:${{ github.run_number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Latest Tag**: \`$DOCKER_REPO:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Number**: \`${{ github.run_number }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Steps Completed:" >> $GITHUB_STEP_SUMMARY
          echo "1. ✅ Code checkout" >> $GITHUB_STEP_SUMMARY
          echo "2. ✅ Python setup" >> $GITHUB_STEP_SUMMARY
          echo "3. ✅ Dependencies installed" >> $GITHUB_STEP_SUMMARY
          echo "4. ✅ Unit tests passed" >> $GITHUB_STEP_SUMMARY
          echo "5. ✅ Docker image built" >> $GITHUB_STEP_SUMMARY
          echo "6. ✅ Docker image pushed" >> $GITHUB_STEP_SUMMARY
          echo "7. ✅ Run Cleanup Script" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Deleted Docker Tags" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "- Pull the Docker image (specific version):" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "  docker pull $DOCKER_REPO:${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "- Pull the latest image:" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "  docker pull $DOCKER_REPO:latest" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "- Run the Docker image (specific version):" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "  docker run -p 5000:5000 $DOCKER_REPO:${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "- Run the Docker image (latest):" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "  docker run -p 5000:5000 $DOCKER_REPO:latest" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          
